name: Docker Image CI

on:
  repository_dispatch:
  workflow_dispatch:
  
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@main

#    - name: Set up QEMU
#      uses: docker/setup-qemu-action@v2
     

    - name: Clone source code
      run: |
        git clone https://github.com/maxmib/docker-typecho-alpine-s6.git typecho
        git clone https://github.com/ttys3/typecho.git typecho/typecho
       
    - name: login
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    
    - name: Build the Docker image
      id: build
      run: | 
        cd typecho
        chmod +x build.sh
        bash build.sh
     
